### ISSUE TITLE
Hvordan bestemmer man hvor den skal downloades når man bruger mac?

### ISSUE THREAD

**Issue by Salling3650** [Vulpesdk/24syv-downloader#1]
Har fået programmet til at virke og har downloadet Den korte radioavis. txt men hvordan finder man den?

**Comment by Vulpesdk** [comment]
Downloaderen virker desværre ikke mere da programmerne ikke længere er
offentligt tilgængelige. Du kan dog benytte dig af R8dio, som har alle
programmerne :)
Venlig hilsen
Rune Vium Søndergaard
